### ISSUE TITLE
Problem signing in

### ISSUE THREAD

**Issue by shizdev** [atlx/discord-term#88]
TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\structures\Guild.js:307:68)
    at new Guild (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\structures\Guild.js:74:12)
    at ClientDataManager.newGuild (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\ClientDataManager.js:26:19)
    at ReadyHandler.handle (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:20:91)
    at WebSocketPacketManager.handle (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\Timam\AppData\Roaming\npm\node_modules\discord-term\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (node:events:327:20)
    
   i get this error when trying to sign in. only gives the error when trying it with a specific token, others i tried work

**Comment by TheGamingCoderNoob** [comment]
I'm having the same issue!

**Comment by bitonalbean** [comment]
same here on void linux 32-bit. i've tried both a global install (requiring sudo) and a local install and the problem remains

> i get this error when trying to sign in. only gives the error when trying it with a specific token, others i tried work
interesting. the tokens that work and the token that doesn't, what type are they? i've only tried with a user token

**Comment by shizdev** [comment]
> same here on void linux 32-bit. i've tried both a global install (requiring sudo) and a local install and the problem remains
> 
> > i get this error when trying to sign in. only gives the error when trying it with a specific token, others i tried work
> 
> interesting. the tokens that work and the token that doesn't, what type are they? i've only tried with a user token

both are user tokens

**Comment by Sahithium-Z** [comment]
This problem is also happening for me, I'm on Arch 64 bit.

**Comment by ChristianGrieger** [comment]
So what exactly is the problem?

**Comment by ochen1** [comment]
Does anyone have an update on this issue? What is the problem? Is there a solution? Is this issue caused by upstream libraries (`discord.js`)?

**Comment by ochen1** [comment]
Okay, I found a quick dirty temporary hacky solution to this issue. I'm not too familiar with this project though, so I won't bother on finding out the reasons for this issue or the potential solutions.

Just edit the file containing the error according to the traceback (it should be in the second line of the traceback, after the error message, for me it's `$HOME/node_modules/discord.js/src/client/ClientDataManager.js`).

Replace the following:
```js
guild.channels.set(channel.id, channel);
```

With the following:
```js
if (channel) {
    guild.channels.set(channel.id, channel);
}
```

**Comment by atlx** [comment]
May have to do with the last saved channel or a default-picked channel when loading your first guild. This may occur for some users on guilds with unexpected channels to the app. I haven't been very active on this project, but I will pick it up soon, don't worry.

**Comment by HexagonWin** [comment]
Hello. I'm on `Trisquel GNU/Linux 9.0 Etiona`, and this issue also happens.

Thanks,
HexagonWin

**Comment by yogeshvar** [comment]
+1

**Comment by atlx** [comment]
This project is going to be archived due to rumors of `d.js` lib's consumers getting banned.
